# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-erb

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/TrailingEmptyLines:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
