default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: pookieboii
  host: localhost
  port: 5432

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  url: <%= ENV['DATABASE_URL'] %>
